### ISSUE TITLE
Run tasks defined in `[tool.tire.tasks]` with `tire run`

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/tire#5]
### Example

```toml
[tool.tire.tasks]
start = "tire run server:main --port 8080"
```

This should allow you to do

```console
$ tire run start
```
